### ISSUE TITLE
Make class nvm a resource

### ISSUE THREAD

**Issue by dsbaars** [artberri/puppet-nvm#11]
Currently it is not possible to add nvm to more than one user because nvm is a class and not a resource

To reproduce, let users be an array of usernames and versions an array of node.js versions:

``` puppet
each( $nvm['users'] ) |$user| {
    class { 'nvm':
      user => $user
    }

    each( $nvm['versions'] ) |$version| {
      nvm::node::install { $version:
        user => $user,
        require => Class['nvm']
      }
    }
  }
```

**Comment by artberri** [comment]
This plugin is not maintained anymore, sorry for the inconvenience:
https://github.com/artberri/puppet-nvm?tab=readme-ov-file#deprecated-puppet-nvm
