### ISSUE TITLE
Update functionality 

### ISSUE THREAD

**Issue by func0der** [artberri/puppet-nvm#22]
Hey,

I was wondering if this module should have the possibility to update the installed version by itself.
Since not all supported systems support systemd, I would suggest using https://puppet.com/docs/puppet/6/types/schedule.html to trigger the updates on a regular basis.
The old versions should probably removed (optionally) during that process.

What do you think about it?

I am testing the waters here. I do not want to invest time, if that is not a wanted feature for this module or if it is inactive.

**Comment by artberri** [comment]
This plugin is not maintained anymore, sorry for the inconvenience:
https://github.com/artberri/puppet-nvm?tab=readme-ov-file#deprecated-puppet-nvm
